flowchart TD
    A{"Метка энрольнута в динамику (сектор 14)?"}
    A --> |"Да"| B["Читаем значение счётчика (сектор 1)"]
    B --> C{"Значение счётчика совпадает с тем, что в памяти ридера?"}
    C --> |"Да"| D["Пишем новое значение счётчика (сектор 1)"]
    D --> Z["Передаём айди метки в контроллер"]
    C --> |"Нет"| Y["Завершаем работу"]
    A --> |"Нет"| E["Энроллим в динамику (сектор 14)"]
    E --> F["Пишем значение счётчика (сектор 1)"]
    F --> Z